### PR TITLE
Fix try-catch for Windows

### LINKED ISSUE #227: signal.alarm not present on Windows
When running the cluster on Windows 11 (`python manage.py qcluster --run-once`), I get an `AttributeError: module 'signal' has no attribute 'alarm'` error. This is due to the fact that `alarm` is not available on Windows.

`timeout.py`
```python
    def __enter__(self):
        # if the timeout is -1, then there is no timeout and the task will always keep running until it's done or manually killed
        if self._timeout == -1:
            return
        try:
            signal.signal(signal.SIGALRM, self.raise_timeout_exception)
        except AttributeError:  # AttributeError is raised for Windows users
            logger.debug(_("SIGALARM is not available on your platform"))

        signal.alarm(self._timeout)
```

While the `signal.signal` is caught, the `signal.alarm` is not.

This is also linked to https://github.com/django-q2/django-q2/pull/223.

### PR DESCRIPTION
**Pull request by ethrgeist**
Need both `ValueError` to catch `signal.signal` not available and `AttributeError` to catch `signal.SIGALRM` missing.

Fixes #227 introduced by #223

### CODE REVIEW

**Comment by ethrgeist** [comment]
Fixed the linter complaint. :)
